image: node:18

stages:
  - test
  - build
  - deploy

before_script:
  - apt-get update && apt-get install -y openssh-client
  - npm install
  - |
    PEM_KEY_PATH=~/key.pem
    echo "$AZURE_PRIVATE_KEY_B64" | base64 -d > $PEM_KEY_PATH
    chmod 600 $PEM_KEY_PATH

    if ! ssh-keygen -yf $PEM_KEY_PATH > /dev/null; then
      echo "ERROR: Private key is invalid or not in a supported format."
      exit 1
    fi

test:
  stage: test
  script:
    - npm run test -- --coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
  only:
    - main

build:
  stage: build
  dependencies:
    - test
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  only:
    - main

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - ssh -i $PEM_KEY_PATH -o StrictHostKeyChecking=no azureuser@$VM_PUBLIC_IP "sudo rm -rf /var/www/html/*"
    - scp -i $PEM_KEY_PATH -o StrictHostKeyChecking=no -r build/* azureuser@$VM_PUBLIC_IP:/var/www/html/
    - ssh -i $PEM_KEY_PATH -o StrictHostKeyChecking=no azureuser@$VM_PUBLIC_IP "sudo systemctl restart apache2"
  only:
    - main