# Generated by Django 5.2.7 on 2025-11-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stripeaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupid',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dater',
            name='ai_degree',
            field=models.TextField(blank=True, default='max'),
        ),
        migrations.AlterField(
            model_name='dater',
            name='dating_strengths',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='dating_weaknesses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='interests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='nerd_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='past',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='relationship_goals',
            field=models.TextField(blank=True, default=''),
        ),
    ]
