# Generated by Django 5.2.7 on 2025-11-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cupid_stripe_account_id_alter_dater_ai_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dater',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('dating', 'Dating'), ('married', 'Married')], default='single', max_length=10),
        ),
    ]
