# Generated by Django 5.0.2 on 2024-02-21 17:18

from django.db import migrations
from django.contrib.auth.hashers import make_password



def dummy_dater1(User, Dater):
    user1 = User(
        username = 'dater1',
        password = make_password('password'),
        email = 'bob@cupid_code.com',
        first_name = 'Bob',
        last_name = 'The Builder',
    )
    user1.save()

    dater1 = Dater(
        user = user1,
        phone_number = '1234567890',
        budget = 50,
        communication_preference = 0,
        description = 'I like to build things in my spare time.',
        dating_strengths = 'Building things is cool',
        dating_weaknesses = 'Not everyone likes to talk about building things all the time.',
        interests = 'Carpentry',
        past = "I've never dated in my whole life.",
        nerd_type = 'building',
        relationship_goals = 'Find the one',
        ai_degree = 'I need all the help',
        cupid_cash_balance = 200,
        location = 'Logan, UT',
        average_rating = 4.3,
        suspended = False,
    )

    #This portion should happen automatically, outside of migrations
    dater1.user.role = "Dater"
    dater1.user.save()

    dater1.save()

def dummy_dater2(User, Dater):
    user2 = User(
        username = 'dater2',
        password = make_password('password'),
        email = 'Manny@cupid_code.com',
        first_name = 'Handy',
        last_name = 'Manny',
    )
    user2.save()

    dater2 = Dater(
        user = user2,
        phone_number = '1223334444',
        budget = 50,
        communication_preference = 0,
        description = 'I fix things for people around town',
        dating_strengths = 'Helping people is cool',
        dating_weaknesses = 'I do not know how to do it',
        interests = 'Tools',
        past = "I have been on many dates and in a few relationships. They all ended poorly.",
        nerd_type = 'building',
        relationship_goals = 'Find a girlfriend and see how it goes',
        ai_degree = "I don't need your help",
        cupid_cash_balance = 20,
        location = 'Logan, UT',
        average_rating = 3.3,
        suspended = False,
    )

    #This portion should happen automatically, outside of migrations
    dater2.user.role = "Dater"
    dater2.user.save()

    dater2.save()

def dummy_daters(apps, schema_editor):
        User = apps.get_model('api', 'User')
        Dater = apps.get_model('api', 'Dater')
        dummy_dater1(User,Dater)
        dummy_dater2(User,Dater)

def dummy_quests(apps, schema_editor):
    Quest = apps.get_model('api', 'Quest')
    quest = Quest(
        budget = 20,
        items_requested = 'flowers',
        pickup_location = 'outside'
    )
    quest.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dummy_quests),
        migrations.RunPython(dummy_daters),
    ]
