# Generated by Django 5.0.2 on 2024-03-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240221_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupid',
            name='accepting_gigs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cupid',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cupid',
            name='cupid_cash_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cupid',
            name='gig_range',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cupid',
            name='gigs_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cupid',
            name='gigs_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cupid',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cupid',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cupid',
            name='status',
            field=models.IntegerField(choices=[(0, 'Offline'), (1, 'Gigging'), (2, 'Available')], default=0),
        ),
    ]
