# Generated by Django 5.0.2 on 2024-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240221_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupid',
            name='gig_range',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
